/**
 * Loads KANJIDIC2 entries: the fallback for worksheet labels on kanji that
 * aren't in your renshuu kanji decks.
 *
 * Your own renshuu data is always preferred; this only fills gaps. The two
 * agree closely — the first meaning matches renshuu's on 685 of 687 kanji
 * checked — because renshuu's kanji meanings appear to come from KANJIDIC2 too.
 *
 * Data derived from KANJIDIC2 (EDRDG, CC BY-SA 4.0), served from
 * public/data/kanjidic/ and generated by scripts/kanjidic.ts.
 */

import { loadByCharacter } from './buckets.ts'
import type { KanjiEntry } from '../types/kanji.ts'

export function loadKanjidic(
  chars: Iterable<string>,
): Promise<Map<string, KanjiEntry>> {
  return loadByCharacter<KanjiEntry>('kanjidic', chars)
}
