/**
 * Loads stroke-order data for the worksheet page.
 *
 * The data is derived from KanjiVG (CC BY-SA 3.0) and served by this site from
 * public/data/strokes/, generated by scripts/strokes.ts. See the LICENSE file
 * there.
 *
 * ## Why not load from a public CDN
 *
 * That's the obvious route, and it doesn't work reliably: jsDelivr rejects the
 * KanjiVG repository as over its 50 MB package limit. Characters already in its
 * cache load; others return 403. A worksheet that silently drops stroke order
 * for less common kanji is worse than having none, so the paths are extracted
 * once from a pinned release and served from here.
 */

import { bucketFor } from './strokeData.ts'
import type { StrokeBucket } from './strokeData.ts'

const STROKES_URL = `${import.meta.env.BASE_URL}data/strokes/`

/** One request per bucket, shared by every character that needs it. */
const bucketCache = new Map<string, Promise<StrokeBucket>>()

function loadBucket(bucket: string): Promise<StrokeBucket> {
  let pending = bucketCache.get(bucket)
  if (!pending) {
    pending = fetch(`${STROKES_URL}${bucket}.json`)
      // A missing bucket means no character in that block has data (Latin
      // letters, say). That's an empty result, not an error.
      .then((response) => (response.ok ? response.json() : {}))
      .catch(() => ({}))
    bucketCache.set(bucket, pending)
  }
  return pending
}

/**
 * Stroke paths for every character given. Characters KanjiVG doesn't cover are
 * absent from the result, and simply get no stroke-order row.
 */
export async function loadStrokes(
  chars: Iterable<string>,
): Promise<Map<string, string[]>> {
  const unique = [...new Set(chars)]
  const buckets = [...new Set(unique.map(bucketFor))]
  const loaded = await Promise.all(buckets.map(loadBucket))

  const byBucket = new Map(buckets.map((bucket, i) => [bucket, loaded[i]]))
  const result = new Map<string, string[]>()
  for (const char of unique) {
    const strokes = byBucket.get(bucketFor(char))?.[char]
    if (strokes?.length) result.set(char, strokes)
  }
  return result
}
