/**
 * Loads stroke-order data for the worksheet page.
 *
 * The data is derived from KanjiVG (CC BY-SA 3.0) and served by this site from
 * public/data/strokes/, generated by scripts/strokes.ts. See the LICENSE file
 * there.
 *
 * ## Why not load from a public CDN
 *
 * That's the obvious route, and it doesn't work reliably: jsDelivr rejects the
 * KanjiVG repository as over its 50 MB package limit. Characters already in its
 * cache load; others return 403. A worksheet that silently drops stroke order
 * for less common kanji is worse than having none, so the paths are extracted
 * once from a pinned release and served from here.
 */

import { loadByCharacter } from './buckets.ts'

/**
 * Stroke paths for every character given. Characters KanjiVG doesn't cover are
 * absent from the result, and simply get no stroke-order row.
 */
export async function loadStrokes(
  chars: Iterable<string>,
): Promise<Map<string, string[]>> {
  const loaded = await loadByCharacter<string[]>('strokes', chars)
  for (const [char, paths] of loaded) {
    if (!paths.length) loaded.delete(char)
  }
  return loaded
}
